# Configurações gerais do projeto

log_level: INFO

paths:
  input_dir: data/principal
  analysis_and_recommendation_dir: data/ar
  examples_dir: data/exemplos
  output_dir: relatorios
  logs: logs/execucao.log

pdf:
  template_first_page: templates/primeira_pagina.pdf
  template_dimension_page: templates/template_dimensao.html
  css_style: templates/estilo.css
